name: Lint notebooks
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
    - run: "make interactive='' check-notebooks || echo 'Discarding errors for now but will be enforced at some point.'"
  flakeheaven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
    - run: "make interactive='' flakeheaven || echo 'Discarding errors for now but will be enforced at some point.'"
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
    - run: "make interactive='' black || echo 'Discarding errors for now but will be enforced at some point.'"

